[package]
name = "constvec"
version = "0.1.14"
edition = "2021"
description = "no heap vec in const expr"
author = "Bruce0203 <brucefreedy@gmail.com>"
repository = "https://github.com/Bruce0203/constvec"
license = "MIT"

[dependencies]
